### ISSUE TITLE
Failed to activate the build-cmd package

### ISSUE THREAD

**Issue by TomaszKozik** [idleberg/atom-build-cmd#4]
[Enter steps to reproduce:]

1. Install with git and yarn by documentation: https://atom.io/packages/build-cmd
2. Restart atom

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [build-cmd](https://github.com/idleberg/atom-build-cmd) package 0.5.2

### Stack Trace

Failed to activate the build-cmd package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:146072)
    at Object.satisfyDependencies (/packages/build-cmd/lib/provider.js:44:3)
    at Object.activate (/packages/build-cmd/lib/provider.js:36:10)
    at Package.activateNow (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3175323)
    at measure (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174735)
    at Package.measure (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3172366)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174595)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174538)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:382705)
    at config.transactAsync (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:382321)
    at Config.transactAsync (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:332491)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:382271)
    at PackageManager.activate (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:381889)
    at t.loadState.then (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:1:696488)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
build-cmd 0.5.2 
```

**Comment by idleberg** [comment]
Did you run `yarn` inside the cloned plugin folder? If you did, there should be a `node_modules/atom-package-deps` folder.
